theme = "soho"
baseurl = "/"
languageCode = "en"
title = "Elizabeth Agey"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

# disqusShortname = "anthroliz"
canonifyURLs=true
publishDir="docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title = "Elizabeth Agey"
  description = "Anthropologist"
  keyword = "educator,researcher,higher-education"
  # gravatar = "soho@example.com"
  profilePicture = "images/elizabeth.jpg"
  copyright = "E. Agey"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  builtWith = true
  mainSections = ["main"]
  rtl = false

## Set custom theme color.
# themeColor = "#fc2803" #red
# themeColor = "#db8a0f" #orange

  [[params.socialIcons]]
  icon = "fa fa-envelope"
  title = "Email"
  url = "mailto:eagey@ucsb.edu"
  
  [[params.socialIcons]]
  icon = "fa-researchgate"
  title = "Research Gate"
  url = "https://www.researchgate.net/profile/Elizabeth_Agey"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/anthroliz"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/anthroliz"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]
  
  [[menu.main]]
  name = "Research"
  weight = 100
  identifier = "research"
  url = "/research/"

  #[[menu.main]]
  #name = "Categories"
  #weight = 200
  #identifier = "categories"
  #url = "/categories/"

  #[[menu.main]]
  #name = "Tags"
  #weight = 200
  #identifier = "tags"
  #url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "CV"
  identifier = "cv"
  weight = 200
  url = "/CV.pdf"
  
  [[menu.main]]
  name = "Teaching"
  identifier = "teaching"
  weight = 20
  url = "/teaching/"  

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
