theme = "soho"
baseurl = "https://anthroliz.github.io/"
languageCode = "en"
title = "Elizabeth Agey"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

# disqusShortname = "anthroliz"
canonifyURLs=true
publishDir="docs"
# ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
title = "Elizabeth Agey"
description = "Biological Anthropologist"
# gravatar = "soho@example.com"
images = ["images/profile.png"]
profilePicture = "images/octocat.png"
copyright = "E. Agey"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
# mainSections = ["main"]

## Set custom theme color.
# themeColor = "#fc2803" #red
themeColor = "#db8a0f" #orange

  [[params.socialIcons]]
  icon = "fa-envelope"
  title = "Email"
  url = "mailto:eagey@ucsb.edu"
  
  [[params.socialIcons]]
  icon = "fa-researchgate"
  title = "Research Gate"
  url = "https://www.researchgate.net/profile/Elizabeth_Agey"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/anthroliz"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/anthroliz"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]
  
  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 20
  url = "/contact/"
  
  [[menu.main]]
  name = "Teaching"
  identifier = "teaching"
  weight = 20
  url = "/teaching/"  

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
